### ISSUE TITLE
在新版pydantic下报错

### ISSUE THREAD

**Issue by ninthseason** [mobyw/nonebot-adapter-mail#6]
`nonebot-adapter-mail`版本 1.0.0a5

在`pydantic==2.10.3(pydantic-core==2.27.1)`环境下无法解析邮件
降级`pydantic`至`pydantic==2.9.2(pydantic_core==2.23.4)`则正常工作

报错如下：
```
12-04 17:13:24 [ERROR] nonebot | Mail | Bot xxx@qq.com error while fetching mail
Traceback (most recent call last):
  File "/home/yzy/bin/puzzle-mail-bot/bot.py", line 16, in <module>
    nonebot.run()
  File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/nonebot/drivers/fastapi.py", line 188, in run
    uvicorn.run(
  File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/yzy/miniforge3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/home/yzy/miniforge3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
> File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/nonebot/adapters/mail/adapter.py", line 85, in _check_mailbox
    await self._fetch_new_mail(bot)
  File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/nonebot/adapters/mail/adapter.py", line 122, in _fetch_new_mail
    mail = await bot.get_mail_of_uid(mail_uid)
  File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/nonebot/adapters/mail/bot.py", line 462, in get_mail_of_uid
    mail = parse_byte_mail(response.lines[1])
  File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/nonebot/adapters/mail/utils.py", line 128, in parse_byte_mail
    return Mail(
  File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/home/yzy/bin/puzzle-mail-bot/.venv/lib/python3.12/site-packages/pydantic/_internal/_mock_val_ser.py", line 100, in __getattr__
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `Mail` is not fully defined; you should define `Message`, then call `Mail.model_rebuild()`.

For further information visit https://errors.pydantic.dev/2.10/u/class-not-fully-defined
```

**Comment by ninthseason** [comment]
升级 nonebot-adapter-mail 至 1.0.0a6 解决问题
